version: "3"

services:
  web:
    build: fastapi
    ports:
      - 8000:8000
    networks:
      - dokploy-network
    depends_on:
      - ollama
    environment:
      - API_KEY=${API_KEY}
    restart: always
  ollama:
    build: ollama
    ports:
      - 11434:11434
    entrypoint: ["/usr/bin/bash", "/pull-llama3.sh"]
    networks:
      - dokploy-network
    restart: always

networks:
  dokploy-network:
    external: true
